spring:
  application:
    name: SalonManager

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/salon_booking
    username: postgres
    password: postgres


logging:
  level:
    org.springframework.security: DEBUG



app:
  jwt:
    secret: bXktc2Fsb24tbWFuYWdlci1wcm9qZWN0LXNlY3VyaXR5LXNlY3JldC1rZXl3b3JkLWZvci1qd3Qtc2VydmljZQ==
    expiration: 300000
    refresh-expiration : 604800000


server:
  port: 8080

